Getting Docker build to work

diff --git a/bin/rhasspy-voltron b/bin/rhasspy-voltron
--- a/bin/rhasspy-voltron
+++ b/bin/rhasspy-voltron
@@ -1,12 +1,90 @@
 #!/usr/bin/env bash
-if [[ -z "${rhasspyvoltron_dir}" ]]; then
-    this_dir="$( cd "$( dirname "$0" )" && pwd )"
-    rhasspyvoltron_dir="${this_dir}/../lib/rhasspyvoltron"
+
+# Directory of *this* script
+this_dir="$( cd "$( dirname "$0" )" && pwd )"
+src_dir="$(realpath "${this_dir}/..")"
+
+config_home="${XDG_CONFIG_HOME}"
+if [[ -z "${config_home}" ]]; then
+    config_home="${HOME}/.config"
 fi
 
-# Include mitlm and phonetisaurus
-export LD_LIBRARY_PATH="${rhasspyvoltron_dir}/mitlm/lib:${rhasspyvoltron_dir}/phonetisaurus/lib:${LD_LIBRARY_PATH}"
-export PATH="${rhasspyvoltron_dir}/mitlm/bin:${rhasspyvoltron_dir}/phonetisaurus/bin:${PATH}"
+# -----------------------------------------------------------------------------
+# Command-line Arguments
+# -----------------------------------------------------------------------------
 
-# Run service
-"${rhasspyvoltron_dir}/rhasspyvoltron" "$@"
+. "${src_dir}/etc/shflags"
+
+DEFINE_string 'profile' '' 'Path to profile' 'p'
+DEFINE_string 'system-profiles' "${src_dir}/rhasspy-server-hermes/profiles" 'Directory with base profile files'
+DEFINE_string 'user-profiles' "${config_home}/rhasspy/profiles" 'Directory with user profile files'
+
+FLAGS "$@" || exit $?
+eval set -- "${FLAGS_ARGV}"
+
+set -e
+
+# -----------------------------------------------------------------------------
+# Load settings
+# -----------------------------------------------------------------------------
+
+profile_name="${FLAGS_profile}"
+if [[ -z "${profile_name}" ]]; then
+    echo "--profile is required"
+    exit 1
+fi
+
+system_profiles="${FLAGS_system_profiles}"
+if [[ -z "${system_profiles}" ]]; then
+    echo "--system-profiles is required"
+    exit 1
+fi
+
+user_profiles="${FLAGS_user_profiles}"
+if [[ -z "${user_profiles}" ]]; then
+    echo "--user-profiles is required"
+    exit 1
+fi
+
+profile_dir="${user_profiles}/${profile_name}"
+
+# -----------------------------------------------------------------------------
+
+# Generate supervisord conf
+conf_path="${profile_dir}/supervisord.conf"
+echo "Generating ${conf_path}"
+
+"${this_dir}/voltron-run" \
+    python3 -m rhasspysupervisor \
+    --profile "${profile_name}" \
+    --system-profiles "${system_profiles}" \
+    --user-profiles "${user_profiles}" \
+    --debug
+
+# Run web server
+"${this_dir}/voltron-run" \
+    python3 -m rhasspyserver_hermes \
+    --profile "${profile_name}" \
+    --system-profiles "${system_profiles}" \
+    --user-profiles "${user_profiles}" \
+    --web-dir "${src_dir}/web" \
+    "$@" \
+    &
+
+# Kill the process above when this terminal exits
+web_pid=$!
+
+function finish {
+    kill "${web_pid}"
+}
+
+trap finish EXIT
+
+# Run assistant
+log_path="${profile_dir}/supervisord.log"
+pid_path="${profile_dir}/supervisord.pid"
+"${this_dir}/voltron-run" \
+    supervisord \
+    --configuration "${conf_path}" \
+    --logfile "${log_path}" \
+    --pidfile "${pid_path}"
